/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wongeun_com_androidwithffplay_NDKAdapter */

#ifndef _Included_wongeun_com_androidwithffplay_NDKAdapter
#define _Included_wongeun_com_androidwithffplay_NDKAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wongeun_com_androidwithffplay_NDKAdapter
 * Method:    setDataSource
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_wongeun_com_androidwithffplay_NDKAdapter_setDataSource
  (JNIEnv *, jclass, jstring);

/*
 * Class:     wongeun_com_androidwithffplay_NDKAdapter
 * Method:    play
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_wongeun_com_androidwithffplay_NDKAdapter_play
  (JNIEnv *, jclass, jobject);

/*
 * Class:     wongeun_com_androidwithffplay_NDKAdapter
 * Method:    setPlayingState
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_wongeun_com_androidwithffplay_NDKAdapter_setPlayingState
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
